kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: onlineconf
provisioner: csi.onlineconf.mail.ru
mountOptions:
  - mode=755
parameters:
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
  uri: http://onlineconf.example.com
  ${namespace}: ${pvc.namespace}
---
apiVersion: v1
kind: Secret
metadata:
  name: example-onlineconf-volume-claim
data:
  "username": ...
  "password": ...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-onlineconf-volume-claim
spec:
  storageClassName: onlineconf
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      - name: ...
        ...
        volumeMounts:
        - name: onlineconf-volume
          mountPath: /usr/local/etc/onlineconf
          readOnly: true
      volumes:
      - name: onlineconf-volume
        persistentVolumeClaim:
          claimName: example-onlineconf-volume-claim
